# Fail2Ban Filter configuration file for detecting eq-login failures
# 
# Author: Cedric Francoys
#
# Can be tested with following command: 
# fail2ban-regex /var/log/nginx/access.log /etc/fail2ban/filter.d/eq-login.conf
#

[Definition]
_daemon = eq-login

# regex for failed equal EQ_ERROR_INVALID_USER responses, behind nginx-proxy
failregex = ^[^\s]*\s*<HOST>.*"(POST|GET)\s+[^"]*"\s+401.*$

# empty and mandatory
ignoreregex =