# Fail2Ban configuration file
#
# Author: Cedric Francoys
#
#
# Since version 17.06, Docker creates an iptable chain called DOCKER-USER,
# these rules will be loaded and applied before any rules created by Docker daemon.
# @see https://docs.docker.com/network/iptables/
#

# Fail2Ban action for Docker-published HTTP services.

[INCLUDES]

before = iptables.conf

[Definition]

type = multiport

[Init]

chain = DOCKER-USER
blocktype = DROP