FROM wordpress:6.1.1-php8.0

LABEL Description="WordPress 6.1.1 with Apache UID and GID injection" \
      Maintainer="Cedric Francoys <cedricfrancoys@gmail.com>" \
      License="Apache License 2.0" \
      Version="1.0"

ARG apache_uid
ARG apache_gid

RUN rm -rf /var/lib/apt/lists/* \
    && apt-get -o Acquire::Retries=3 update \
    && apt-get -o Acquire::Retries=3 install -y --no-install-recommends \
        git \
        procps \
        netcat-traditional \
        vim \
    && /usr/sbin/usermod -u "$apache_uid" www-data \
    && /usr/sbin/groupmod -g "$apache_gid" www-data \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-install pdo pdo_mysql

COPY ./mpm_prefork.conf /etc/apache2/mods-available/
