FROM wordpress:6.1.1-php8.0

LABEL Description="WordPress 6.1.1 with Apache UID and GID injection" \
      Maintainer="Cedric Francoys <cedricfrancoys@gmail.com>" \
      License="Apache License 2.0" \
      Version="1.0"

ARG apache_uid
ARG apache_gid

RUN printf '%s\n' \
        'deb [check-valid-until=no] https://archive.debian.org/debian bullseye main' \
        'deb [check-valid-until=no] https://archive.debian.org/debian bullseye-updates main' \
        > /etc/apt/sources.list \
    && rm -f /etc/apt/sources.list.d/* \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        procps \
        netcat-traditional \
        vim \
    && /usr/sbin/usermod -u "$apache_uid" www-data \
    && /usr/sbin/groupmod -g "$apache_gid" www-data \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-install pdo pdo_mysql

COPY ./mpm_prefork.conf /etc/apache2/mods-available/
